const Product_dis = [
  {
    id: 1,
    name: "puma sport shoes",
    price: 5999,
    imgs: "/imgs/prdouct2.jpg",
    reviews: "120",
  },
  {
    id: 2,
    name: "Addidas shoes",
    price: 2999,
    imgs: "/imgs/product1.jpg",
    reviews: "150",
  },
  {
    id: 3,
    name: "Campus Running shoes",
    price: 3999,
    imgs: "/imgs/product3.jpg",
    reviews: "126",
  },
  {
    id: 4,
    name: "puma sport shoes",
    price: 6999,
    imgs: "/imgs/product4.jpg",
    reviews: "1K",
  },
  {
    id: 5,
    name: "sport shoes",
    price: 19999,
    imgs: "/imgs/product5.jpg",
    reviews: "108",
  },
  {
    id: 6,
    name: "puma sport shoes",
    price: 9999,
    imgs: "/imgs/product6.png",
    reviews: "130",
  },
];

export const productTotal = [
  {
    id: 1,
    name: "puma sport shoes",
    price: 2699,
    imgs: "/imgs/prdouct10.jpg",
    reviews: "120",
  },
  {
    id: 2,
    name: "Adidas sport shoes",
    price: 6299,
    imgs: "/imgs/product11.avif",
    reviews: "120",
  },
  {
    id: 3,
    name: "puma sport shoes",
    price: 5999,
    imgs: "/imgs/product12.avif",
    reviews: "120",
  },
  {
    id: 4,
    name: "Adidas sport shoes",
    price: 2699,
    imgs: "/imgs/product13.jpg",
    reviews: "120",
  },
  {
    id: 5,
    name: "puma sport shoes",
    price: 2999,
    imgs: "/imgs/product14.avif",
    reviews: "120",
  },
  {
    id: 6,
    name: "Adidas sport shoes",
    price: 2869,
    imgs: "/imgs/product15.avif",
    reviews: "120",
  },
  {
    id: 7,
    name: "puma sport shoes",
    price: 2199,
    imgs: "/imgs/product16.avif",
    reviews: "120",
  },
  {
    id: 8,
    name: "puma sport shoes",
    price: 2959,
    imgs: "/imgs/product17.avif",
    reviews: "120",
  },
  {
    id: 9,
    name: "Adidas sport shoes",
    price: 3999,
    imgs: "/imgs/product18.avif",
    reviews: "120",
  },
  {
    id: 10,
    name: "puma sport shoes",
    price: 9299,
    imgs: "/imgs/product19.avif",
    reviews: "120",
  },
  {
    id: 11,
    name: "Fila sport shoes",
    price: 5829,
    imgs: "/imgs/product20.jpg",
    reviews: "120",
  },
  {
    id: 12,
    name: "Redtape sport shoes",
    price: 6201,
    imgs: "/imgs/product21.jpg",
    reviews: "120",
  },
  {
    id: 13,
    name: "puma sport shoes",
    price: 10199,
    imgs: "/imgs/prdouct2.jpg",
    reviews: "120",
  },
  {
    id: 14,
    name: "Fila sport shoes",
    price: 2599,
    imgs: "/imgs/product1.jpg",
    reviews: "120",
  },
  {
    id: 15,
    name: "Redtape sport shoes",
    price: 5999,
    imgs: "/imgs/product3.jpg",
    reviews: "120",
  },
  {
    id: 16,
    name: "Fila sport shoes",
    price: 2999,
    imgs: "/imgs/product4.jpg",
    reviews: "120",
  },
  {
    id: 17,
    name: "Redtape sport shoes",
    price: 9999,
    imgs: "/imgs/product5.jpg",
    reviews: "120",
  },
  {
    id: 18,
    name: "Fila sport shoes",
    price: 3999,
    imgs: "/imgs/product6.png",
    reviews: "120",
  },
  {
    id: 19,
    name: "puma sport shoes",
    price: 6299,
    imgs: "/imgs/product7.avif",
    reviews: "120",
  },
  {
    id: 20,
    name: "Redtape sport shoes",
    price: 1199,
    imgs: "/imgs/product8.jpg",
    reviews: "120",
  },
];

export default Product_dis;
